name: Gatsby build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build, Deploy, Slack notify
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # chache node_modules
      - name: Cache multiple paths
        uses: actions/cache@v2
        id: node_module_cache
        with: 
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      # Install Package
      - name: npm install
        run: |
          cd blog
          npm ci
      # Run build
      - name: npm build
        run: |
          cd blog/
          npm run build --if-present
      # Archive Production Artifact
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: public
          path: blog/public
      # SSHキーのインストール
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.0.1
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      # rsyncの実行
      - name: rsync
        run: rsync -auvz --delete blog/public/ ${{ secrets.REMOTE_USER }}@psbss.mixh.jp:./www/ue-y.me/blog/
      # Slack notify
      - name: Slack Incoming Webhook
        if: success()
        uses: tokorom/action-slack-incoming-webhook@v1.1.3
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          text: ブログの更新が完了したよ！
          attachments: |
            [
              {
                "color": "good",
                "author_name": "${{ github.actor }}",
                "author_icon": "${{ github.event.sender.avatar_url }}",
                "fields": [
                  {
                    "title": "Commit Message",
                    "value": "${{ env.COMMIT_MESSAGE }}"
                  },
                  {
                    "title": "GitHub Actions URL",
                    "value": "${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}"
                  },
                  {
                    "title": "Blog URL"
                    "value": "https://blog.ue-y.me/"
                  }
                ]
              }
            ]
