name: Gatsby build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: deploy to public branch
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and build
      run: |
        cd blog
        npm ci
        npm run build --if-present
      env:
        CI: true
