name: Gatsby build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: deploy to public branch
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: gatsby build
      with:
        deploy-branch: public
