name: Gatsby build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: build files
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and build
      run: |
        cd blog
        npm ci
        npm run build --if-present
      env:
        CI: true

  upload:
    name: upload outputs
    runs-on: ubuntu-latest

    steps:
      run: cd blog
    - name: Archive Production Artifact
      uses: actions/upload-artifact@master
      with:
        name: public
        path: public