name: Gatsby build

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

jobs:
  slack_notification:
    name: Slack notification
    runs-on: ubuntu-latest
    if: contains(github.head_ref, 'ci/')
    steps:
      - uses: technote-space/workflow-conclusion-action@v2
      - name: Slack Incoming Webhook
        uses: 8398a7/action-slack@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: custom
          author_name: Github Actions infomation
          custom_payload: |
            {
              attachments: [
                {
                  pretext: "ブログの更新が完了したよ！",
                  color: "good",
                  author_name: "${{ github.actor }}",
                  author_icon: "${{ github.event.sender.avatar_url }}",
                  fields: [
                    {
                      title: "PR Title & URL",
                      value: "<${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }} #${{ github.event.number }}>",
                      short: false
                    },
                    {
                      title: "GitHub Actions URL",
                      value: "${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}",
                      short: false
                    },
                    {
                      title: "Blog URL",
                      value: "https://blog.ue-y.me/",
                      short: false
                    }
                  ]
                }
              ] 
            }
