name: Gatsby build

on:
  push:
    branches:
      - main

jobs:
  # package install & Build
  build:
    name: package install & Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # chache node_modules
      - name: Cache multiple paths
        uses: actions/cache@v2
        id: node_module_cache
        with: 
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      # Install Package
      - name: npm install
        run: npm ci
      # Run build
      - name: npm build
        run: npm run build --if-present
      # Archive Production Artifact
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: public
          path: public

  # Sync with AWS S3
  sync-with-s3:
    name: Sync with AWS S3
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: public
          path: ~/public/
      - name: AWS configure credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: S3 sync
        run: aws s3 sync ~/public/ ${{ secrets.AWS_S3_BUCKET_NAME }} --delete

  # Slack notification
  slack_notification:
    name: Slack notification
    if: always()
    runs-on: ubuntu-latest
    needs: sync-with-s3
    steps:
      - uses: technote-space/workflow-conclusion-action@v2
      - name: Slack Incoming Webhook
        uses: 8398a7/action-slack@v3
        if: env.WORKFLOW_CONCLUSION == 'success'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: custom
          author_name: Github Actions infomation
          custom_payload: |
            {
              attachments: [
                {
                  pretext: "ブログの更新が完了したよ！",
                  color: "good",
                  author_name: "${{ github.actor }}",
                  author_icon: "${{ github.event.sender.avatar_url }}",
                  fields: [
                    {
                      title: "GitHub Actions URL",
                      value: "${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}",
                      short: false
                    },
                    {
                      title: "Blog URL",
                      value: "https://blog.ue-y.me/",
                      short: false
                    }
                  ]
                }
              ] 
            }
