name: Gatsby build dry run

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pull_request:
    name: Package install / Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - name: npm install
        run: npm ci
      - name: npm build
        run: npm run build --if-present
