name: Gatsby build dry run

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pull_request:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '14', '16' ]

    name: Node version ${{ matrix.node }} 
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - name: npm install
        run: npm ci
      - name: npm build
        run: npm run build --if-present
